---
:concurrency: 2
production:
  :concurrency: 4
:queues:
  - [transactions, 3]
  - [accounts, 3]
  - [messages, 3]
:scheduler:
  :schedule:
    schedule_latest_transactions:
      cron: '20 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestTransactionsJob
    schedule_latest_accounts:
      cron: '30 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestAccountsJob
    schedule_latest_messages:
      cron: '0 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestMessagesJob
