---
:concurrency: 2
production:
  :concurrency: 3
:queues:
  - [transactions, 2]
  - [accounts, 2]
  - [transaction_categorizer, 1]
  - [messages, 1]
:scheduler:
  :schedule:
    schedule_latest_transactions:
      cron: '*/30 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestTransactionsJob
    schedule_latest_accounts:
      cron: '*/30 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestAccountsJob
