---
:concurrency: 1
production:
  :concurrency: 3
:queues:
  - transactions

:scheduler:
  :schedule:
    schedule_latest_transactions:
      cron: '*/30 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestTransactionsJob
