---
:concurrency: 2
production:
  :concurrency: 4
:queues:
  - [transactions, 2]
  - [accounts, 2]
  - [transaction_categorizer, 1]
  - [messages, 1]
  - [decode_messages, 1]
:scheduler:
  :schedule:
    schedule_latest_transactions:
      cron: '*/35 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestTransactionsJob
    schedule_latest_accounts:
      cron: '*/28 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestAccountsJob
    schedule_latest_messages:
      cron: '*/25 * * * * *'   # Runs once per minute # '0 */5 * * * *'
      class: ScheduleLatestMessagesJob
